/* ---------------------------------------------------- */
/*  Generated by Enterprise Architect Version 13.5 		*/
/*  Created On : 07-lut-2022 20:46:36 				*/
/*  DBMS       : MySql 						*/
/* ---------------------------------------------------- */

SET FOREIGN_KEY_CHECKS=0 
;

/* Drop Tables */

DROP TABLE IF EXISTS `activity` CASCADE
;

DROP TABLE IF EXISTS `sequence_workout` CASCADE
;

DROP TABLE IF EXISTS `tabata_sequence` CASCADE
;

DROP TABLE IF EXISTS `user` CASCADE
;

DROP TABLE IF EXISTS `workout` CASCADE
;

/* Create Tables */

CREATE TABLE `activity`
(
	`activity_id` INT NOT NULL,
	`type` CHAR(1) NOT NULL DEFAULT E,
	`decription` VARCHAR(70) NULL,
	`workout_id` INT NOT NULL,
	`order_in_workout` INT NOT NULL,
	`duration` INT NOT NULL DEFAULT 30,
	CONSTRAINT `PK_activity` PRIMARY KEY (`activity_id` ASC)
)

;

CREATE TABLE `sequence_workout`
(
	`sequence_id` INT NOT NULL,
	`workout_id` INT NOT NULL,
	`order_in_sequence` INT NOT NULL,
	CONSTRAINT `PK_sequence_workout` PRIMARY KEY (`sequence_id` ASC, `workout_id` ASC)
)

;

CREATE TABLE `tabata_sequence`
(
	`sequence_id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(300) NULL,
	CONSTRAINT `PK_tabata_sequence` PRIMARY KEY (`sequence_id` ASC)
)

;

CREATE TABLE `user`
(
	`user_id` INT NOT NULL,
	`username` VARCHAR(60) NOT NULL,
	CONSTRAINT `PK_user` PRIMARY KEY (`user_id` ASC)
)
COMMENT = 'add salt and hash (right DB types for them?)'

;

CREATE TABLE `workout`
(
	`workout_id` INT NOT NULL,
	`name` VARCHAR(50) NOT NULL,
	`description` VARCHAR(300) NULL,
	`prepare_time` INT NOT NULL DEFAULT 0,
	`cycles` INT NOT NULL DEFAULT 1,
	`sets` INT NOT NULL DEFAULT 1,
	`set_time` INT NOT NULL DEFAULT 0,
	`cool_down_time` INT NOT NULL DEFAULT 0,
	`user_id` INT NOT NULL,
	CONSTRAINT `PK_workout` PRIMARY KEY (`workout_id` ASC)
)

;

/* Create Foreign Key Constraints */

ALTER TABLE `activity` 
 ADD CONSTRAINT `FK_activity_workout`
	FOREIGN KEY (`workout_id`) REFERENCES `workout` (`workout_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `sequence_workout` 
 ADD CONSTRAINT `FK_sequence_workout_sequence`
	FOREIGN KEY (`sequence_id`) REFERENCES `tabata_sequence` (`sequence_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `sequence_workout` 
 ADD CONSTRAINT `FK_sequence_workout_workout`
	FOREIGN KEY (`workout_id`) REFERENCES `workout` (`workout_id`) ON DELETE Cascade ON UPDATE Cascade
;

ALTER TABLE `workout` 
 ADD CONSTRAINT `FK_workout_user`
	FOREIGN KEY (`user_id`) REFERENCES `user` (`user_id`) ON DELETE Cascade ON UPDATE Cascade
;

SET FOREIGN_KEY_CHECKS=1 
;
